[package]
name = "serde-file-descriptor-ipc-example"
version = "0.1.0"
authors = ["Walter Smuts <wssmts@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unix-ipc = "0.2.0"
serde = "1.0.117"
